# Generated by Django 4.2.23 on 2025-07-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_transaction_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.TextField(blank=True),
        ),
    ]
